enableColors: true

nmHoistingLimits: workspaces

nodeLinker: node-modules

enableScripts: false

# Suppress warnings for known peer dependency issues
logFilters:
  - pattern: "* doesn't provide @aws-sdk/*"
    level: discard
  - pattern: "* doesn't provide react (p*"
    level: discard
  - pattern: "* doesn't provide react-dom (p*"
    level: discard
  - pattern: "* doesn't provide typescript (p*"
    level: discard
  - pattern: "* doesn't provide @tanstack/react-query (p*"
    level: discard
  - pattern: "* doesn't provide ethers (p*"
    level: discard
  - pattern: "* doesn't provide hardhat-deploy (p*"
    level: discard
  - pattern: "* doesn't provide react-native (p*"
    level: discard
  - pattern: "* doesn't provide fastestsmallesttextencoderdecoder (p*"
    level: discard
  - pattern: "* doesn't provide ws (p*"
    level: discard
  - pattern: "* doesn't provide undici (p*"
    level: discard
  - pattern: "* doesn't provide @types/node (p*"
    level: discard
  - pattern: "* provides * with version *, which doesn't satisfy what * requests"
    level: discard
  - pattern: "Some peer dependencies are incorrectly met*"
    level: discard

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
