enableColors: true

nmHoistingLimits: workspaces

nodeLinker: node-modules

enableScripts: false

# Suppress warnings for known peer dependency issues
logFilters:
  # Deprecation warnings
  - pattern: "* is deprecated*"
    level: discard
  # AWS SDK warnings
  - pattern: "* doesn't provide @aws-sdk/*"
    level: discard
  # React warnings
  - pattern: "* doesn't provide react (p*"
    level: discard
  - pattern: "* doesn't provide react-dom (p*"
    level: discard
  - pattern: "* provides react (p*"
    level: discard
  - pattern: "* provides @types/react (p*"
    level: discard
  # TypeScript warnings
  - pattern: "* doesn't provide typescript (p*"
    level: discard
  # React Query warnings
  - pattern: "* doesn't provide @tanstack/react-query (p*"
    level: discard
  # Ethers warnings
  - pattern: "* doesn't provide ethers (p*"
    level: discard
  - pattern: "* provides ethers (p*"
    level: discard
  # Hardhat warnings
  - pattern: "* doesn't provide hardhat-deploy (p*"
    level: discard
  - pattern: "* provides hardhat-deploy (p*"
    level: discard
  # React Native warnings
  - pattern: "* doesn't provide react-native (p*"
    level: discard
  - pattern: "* doesn't provide @babel/core (p*"
    level: discard
  - pattern: "* doesn't provide @babel/preset-env (p*"
    level: discard
  # Solana warnings
  - pattern: "* doesn't provide fastestsmallesttextencoderdecoder (p*"
    level: discard
  # Network warnings
  - pattern: "* doesn't provide ws (p*"
    level: discard
  - pattern: "* doesn't provide undici (p*"
    level: discard
  # Node types
  - pattern: "* doesn't provide @types/node (p*"
    level: discard
  # AWS S3 warnings
  - pattern: "* provides @aws-sdk/client-s3 (p*"
    level: discard
  # Generic version conflicts
  - pattern: "* provides * with version *, which doesn't satisfy what * requests"
    level: discard
  # Summary warnings
  - pattern: "Some peer dependencies are incorrectly met*"
    level: discard

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
